### ISSUE TITLE
Set a default date time range

### ISSUE THREAD

**Issue by Minoli** [oliver-schoendorn/react-date-time-range-picker#4]
Hi,
How can I set a default date time range (e.g Last 24 hours) on page load (before clicking edit) where it will be highlighted and selected on the left side bar?  
Thanks

**Comment by oliver-schoendorn** [comment]
Hi, 
If you are using an uncontrolled picker, you can use the [`initialState` prop](https://github.com/oliver-schoendorn/react-date-time-range-picker/blob/master/src/Context/Context.ts#L4). If the `initialState.start` and `initialState.end` dates match exactly one of the ranges `from` and `until` values it should highlighted the matched range automatically.

```ts
import React, { FunctionComponent } from 'react'
import {
    DateTimeRangePicker,
    DateTimePickerOptions,
    DateTimeHelper
} from '@oliver-schoendorn/react-date-time-range-picker'

const DateTimePicker: FunctionComponent = () =>
{
    const now = new Date()
    return (
        <DateTimeRangePicker
            onChange={ (start: Date, end: Date) => {
                console.log('Selected date time range', { start, end })
            } }
            options={ { ranges: {
                    'last 60 days': {
                        from: DateTimeHelper.addDays(now, -60),
                        until: now
                    }
            } } }
            initialState={ {
                start: DateTimeHelper.addDays(now, -60),
                end: now
            } }
        >
            <button>Select date</button>
        </DateTimeRangePicker>
    )
}
```

I will update the Readme as soon as I can but it might take a few days.

**Comment by Minoli** [comment]
Thanks a lot. It solved my issue.
