### ISSUE TITLE
Predefined date ranges on the popover

### ISSUE THREAD

**Issue by Minoli** [oliver-schoendorn/react-date-time-range-picker#6]
Hi,
Is there an options to show predefined date ranges on a dropdown and to expand the popover to show the calendar when custom is selected? something like this.

<img width="330" alt="Screenshot 2020-03-16 at 09 54 34" src="https://user-images.githubusercontent.com/9837443/76723235-94468580-676c-11ea-9730-5c6ff37e28ad.png">

**Comment by oliver-schoendorn** [comment]
Hi, that is a little bit tricky with the current implementation.

You would have to overwrite the render method of [DateTimeRangePickerController](https://github.com/oliver-schoendorn/react-date-time-range-picker/blob/master/src/Components/DateTimeRangePickerControlled.tsx#L96) and provide a custom implementation of the [Ranges Component](https://github.com/oliver-schoendorn/react-date-time-range-picker/blob/master/src/Components/Range/Ranges.tsx#L44). 

I think this would be a nice additional feature, so if you plan on implementing that yourself, I would be very happy about a pull request (or some experimental code). I would even be willing to do it myself but that would take me a few days and I would not expect results until next Monday.

**Comment by Minoli** [comment]
Thank you so much for this! I really didn't have time as I was working for a release. When will this be published?

**Comment by Minoli** [comment]
I came across another small issue. When I select a range apart from the topmost one, the active state is not shown in the list of ranges. In the below image I have selected 7 days. Will this be fixed with the new implementation? 

<img width="744" alt="Screenshot 2020-03-22 at 09 00 18" src="https://user-images.githubusercontent.com/9837443/77241682-baac6b00-6c1b-11ea-9b7d-b677c32dbfca.png">

**Comment by oliver-schoendorn** [comment]
I will publish a new version tomorrow. In the current test build the ranges are highlighted properly.

**Comment by oliver-schoendorn** [comment]
`v1.0.0` has just been published and a little example of how to toggle the calendar visibility based on the selected ranges can be [found here](/oliver-schoendorn/react-date-time-range-picker/tree/master/examples/ShowRangesOnlyUnlessCustomRangeIsSelected/ShowRangesOnlyUnlessCustomRangeIsSelected.tsx).

**Comment by Minoli** [comment]
Thanks a lot.
